---
version: "3"

vars:
  SOPS_TASKFILE_RESOURCES_DIR: '{{.ROOT_DIR}}/.taskfiles/sops/resources'

tasks:

  install:
    desc: Install and Configure Mozilla SOPS
    cmds:
      - bash {{.SOPS_TASKFILE_RESOURCES_DIR}}/scripts/install_sops.sh
