---
version: "3"

includes:
  ansible: ../ansible/Taskfile.yaml
  pre-commit: ../pre-commit/Taskfile.yaml

tasks:
  bootstrap:
    desc: Bootstrap the dev container
    cmds:
      - task: pre-commit:init
      - task: pre-commit:update
      - task: ansible:dependencies
