---
kvm:
  hosts:
    pikvm:
      # ansible_host: 10.10.20.50
      ansible_host: pikvm.{{ public_domain }}
  vars:
    ansible_port: 22
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
