---
# Areas
area/docs:
  - changed-files:
    - any-glob-to-any-file:
      - "docs/**/*"
      - "mkdocs.yml"
      - "README.md"
area/ansible:
  - changed-files:
    - any-glob-to-any-file:
      - "lab/provision/ansible/**/*"
area/terraform:
  - changed-files:
    - any-glob-to-any-file:
      - "lab/provision/terraform/**/*"
area/packer:
  - changed-files:
    - any-glob-to-any-file:
      - "lab/provision/packer/**/*"
area/github:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**/*"
# Clusters
cluster/main:
  - changed-files:
    - any-glob-to-any-file:
      - "lab/cluster/**/*"
