---
version: "3"

vars:
  PRE_COMMIT_TASLFILE_RESOURCES_DIR: '{{.ROOT_DIR}}/.taskfiles/pre-commit/resources'

tasks:

  install:
    desc: Install pre-commit onto the system
    cmds:
      - bash {{.PRE_COMMIT_TASLFILE_RESOURCES_DIR}}/scripts/install_pre_commit.sh

  init:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install --install-hooks

  update:
    desc: Update pre-commit hooks
    cmds:
      - pre-commit autoupdate

  run:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files
