---
# lae.proxmox (v1.7.0)
pve_group: pve
pve_repository_line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
pve_remove_subscription_warning: true
pve_extra_packages:
  - sudo
  - ifupdown2
  - ifenslave
  - cloud-init
pve_run_system_upgrades: false
pve_run_proxmox_upgrades: true
pve_check_for_kernel_update: true
pve_reboot_on_kernel_update: true
pve_reboot_on_kernel_update_delay: 60
pve_remove_old_kernels: true
pve_watchdog: none
# pve_watchdog_ipmi_action: power_cycle
# pve_watchdog_ipmi_timeout: 10
pve_zfs_enabled: no
# pve_zfs_options: ""
# pve_zfs_zed_email: ""
# pve_zfs_create_volumes: []
pve_ceph_enabled: true
pve_ceph_repository_line: "deb http://download.proxmox.com/debian/ceph-pacific bullseye main"
pve_ceph_network: "{{ ceph_ip }}/24"
# pve_ceph_cluster_network: ""
pve_ceph_nodes: "{{ pve_group }}"
pve_ceph_mon_group: "{{ pve_group }}"
pve_ceph_mgr_group: "{{ pve_ceph_mon_group }}"
pve_ceph_mds_group: "{{ pve_group }}"
pve_ceph_osds:
  - device: /dev/nvme0n1
    encrypted: false
pve_ceph_pools:
  - name: pve-ceph
    storage: true
    application: rbd
    rule: replicated_rule
    autoscale_mode: "on"
    pgs: 128
    size: 3
    min-size: 2
# pve_ceph_fs: []
# pve_ceph_crush_rules: []
# pve_ssl_private_key: ""
# pve_ssl_certificate: ""
# pve_roles: []
# pve_groups: []
# pve_users: []
# pve_storages: []
pve_datacenter_cfg:
  keyboard: en-us
  language: en
pve_cluster_clustername: pve-cluster
pve_cluster_enabled: true
pve_cluster_addr0: "{{ coro_ip }}"
# pve_cluster_addr1:
pve_manage_hosts_enabled : no
# --interfaces_template: "./templates/pve_interfaces_template.yaml.j2"
# pve_cluster_ha_groups: []
