---
site_name: ol3d's Homelab
site_author: Adam Delo

repo_url: https://github.com/ol3d/home-ops

theme:
    name: material
    locale: en
    palette:
        primary: black
    features:
        - navigation.indexes
        - navigation.sections
        - search.highlight
        - search.share

markdown_extensions:
    - pymdownx.snippets:
        check_paths: true

nav:
    - Home:
        - index.md
    - Setup:
        - setup/index.md
        - Management Node:
            - setup/mgmt/git-repository-setup.md
        - PiKVM:
            - setup/pikvm/pikvm-setup.md
        - Proxmox:
            - setup/proxmox/debian-setup.md
            - setup/proxmox/proxmox-cluster-setup.md
    - Concepts:
        - concepts/index.md
        - Documentation:
            - concepts/documentation/documentation-methodology.md
            - concepts/documentation/documentation-alternatives.md
        - SSH Certificate Authority:
            - concepts/ssh/ssh-certificate-authority.md
        - Visual Studio Code:
            - concepts/.vscode/extensions.md
    - How-to:
        - how-to/index.md
        - Documentation:
            - how-to/documentation/creating-documentation.md
        - Storage:
            - how-to/storage/drive-health.md
            - Backups:
                - how-to/storage/backups/duplicacy-backups.md
    - Reference:
        - reference/index.md
        - Homelab:
            - reference/homelab/index.md
            - Network:
                - reference/homelab/network/network-reference.md
            - Hardware:
                - reference/homelab/hardware/server-rack-reference.md
                - reference/homelab/hardware/hardware-reference.md
            - Services:
                - reference/homelab/services/index.md
                - reference/homelab/services/cloud-services-reference.md
                - reference/homelab/services/self-hosted-services-reference.md
        - Supermicro:
            - reference/supermicro/fan-control.md
            - reference/supermicro/X11SCL-iF.md
        - Cisco:
            - reference/cisco/cisco-ws-2960l-48ts-ll.md
    - Archive:
        - archive/index.md
