---
site_name: home-ops

repo_url: https://github.com/ol3d/home-ops

theme:
    name: material
    palette:
        primary: black
    features:
        - navigation.indexes
        - navigation.sections
        - search.highlight
        - search.share

markdown_extensions:
    - pymdownx.snippets:
        check_paths: true

nav:
    - Home:
        - index.md
    - Setup:
        - setup/index.md
        - Management Node:
            - setup/mgmt/mgmt-setup.md
        - PiKVM:
            - setup/pikvm/pikvm-setup.md
        - Proxmox:
            - setup/proxmox/debian-setup.md
            - setup/proxmox/proxmox-cluster-setup.md
    - Concepts:
        - concepts/index.md
        - Automation:
            - Ansible:
                - concepts/automation/ansible/ansible.md
            - Terraform:
                - concepts/automation/terraform/terraform.md
        - Cloud-init:
            - concepts/cloud-init/cloud-init.md
        - SSH Certificate Authority:
            - concepts/ssh/ssh-certificate-authority.md
        - Storage:
            - concepts/storage/drive-health.md
        - Visual Studio Code:
            - concepts/.vscode/extensions.md
    - How-to:
        - how-to/index.md
        - Documentation:
            - how-to/documentation/creating-documentation.md
    - Reference:
        - reference/index.md
        - Documentation:
            - reference/documentation/documentation-methodology.md
            - reference/documentation/documentation-alternatives.md
        - Network:
            - reference/network/network-reference.md
