---
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  ansible: .taskfiles/ansible
  aws: .taskfiles/aws
  management: .taskfiles/management
  packer: .taskfiles/packer
  pre-commit: .taskfiles/pre-commit
  sops: .taskfiles/sops
  opentofu: .taskfiles/opentofu

tasks:
  default: task --list
