---
version: "3"

includes:
  ansible: lab/base/.taskfiles/AnsibleTasks.yml
  precommit: lab/base/.taskfiles/PreCommitTasks.yml
  terraform: lab/base/.taskfiles/TerraformTasks.yml
  mgmt: lab/base/.taskfiles/MgmtTasks.yml
