---
version: "3"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  precommit: .taskfiles/PreCommitTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
  bootstrap: .taskfiles/BootstrapTasks.yml
  diff: .taskfiles/DiffTasks.yml
  packer: .taskfiles/PackerTasks.yml
