---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/lab/provision/ansible"
  ANSIBLE_RESOURCES_DIR: '{{.ROOT_DIR}}/.taskfiles/ansible/resources'

tasks:

  install:
    desc: Install Ansible onto the system
    vars:
      ANSIBLE_VERSION: "2.17.5"
    cmds:
      - bash {{.ANSIBLE_RESOURCES_DIR}}/scripts/install_ansible.sh {{.ANSIBLE_VERSION}}
    # status:
    #   - command -v "ansible" &> /dev/null

  init:
    desc: Install/Upgrade Ansible Galaxy dependencies
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-galaxy install -r requirements.yml --force
      - ansible-galaxy collection install -r requirements.yml --force
