---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/lab/provision/ansible"

tasks:

  version:
    desc: Output the installed Ansible version
    cmds:
      - ansible --version

  dependencies:
    desc: Install/Upgrade Ansible Galaxy dependencies
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-galaxy install -r requirements.yml --force
      - ansible-galaxy collection install -r requirements.yml --force
