---
- block:
    - name: Update apt repository and cache
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: true
    - name: Check if reboot is required
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
        get_md5: false
    - name: Reboot server if kernel updated
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

- block:
    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ apt_packages }}"
    - name: Install pip packages
      ansible.builtin.pip:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ pip_packages }}"

    - name: Install pre-commit git hook scripts
      ansible.builtin.command:
        cmd: pre-commit install

- block:
    - name: Modify AWS Configuration File
      blockinfile:
        dest: /home/{{ ansible_user }}/.aws/config
        block: |
          [default]
          region = {{ AWS.AWS_REGION }}
          output = json
        backup: false
    - name: Modify AWS Credentials File
      blockinfile:
        dest: /home/{{ ansible_user }}/.aws/credentials
        block: |
          [default]
          aws_access_key_id = {{ AWS.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = {{ AWS.AWS_SECRET_ACCESS_KEY }}
        backup: false

- block:
    - name: Install Mozilla SOPS and Modify Permissions
      get_url:
        url: "https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux"
        dest: /usr/local/bin/sops
        mode: +x

- block:
    - name: Modify gitconfig
      ansible.builtin.template:
        dest: /home/{{ ansible_user }}/.gitconfig
        src: .gitconfig.j2

- block:
    - name: Add Hashicorp GPG Key to trusted Keystore
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add the Hashicorop Linux repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
        state: present
    - name: Update apt repository
      apt:
        force_apt_get: true
