---
- name: set_ro_filesystem
  ansible.builtin.command:
    cmd: /usr/local/bin/ro

- name: set_rw_filesystem
  ansible.builtin.command:
    cmd: /usr/local/bin/rw

- name: Reboot PiKVM
  ansible.builtin.reboot:
  register: rebooted
  when: rebooted is undefined

- name: Restart kvmd
  ansible.builtin.systemd:
    name: kvmd
    state: restarted
  when: rebooted is undefined
