---
# geerlingguy.ntp
ntp_manage_config: true
npm_servers:
  - 2.pfsense.pool.ntp.org

# lae.proxmox
pve_group: pve
pve_repository_line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
pve_remove_subscription_warning: true
pve_extra_packages:
  - sudo
  - ifupdown2
  - ifenslave
  - cloud-init
  - openvswitch-switch
  - python3-jmespath
pve_run_system_upgrades: false
pve_run_proxmox_upgrades: true
pve_check_for_kernel_update: true
pve_reboot_on_kernel_update: true
pve_reboot_on_kernel_update_delay: 60
pve_remove_old_kernels: true
pve_watchdog: none
# pve_watchdog_ipmi_action: power_cycle
# pve_watchdog_ipmi_timeout: 10
pve_zfs_enabled: false
# pve_zfs_options: ""
# pve_zfs_zed_email: ""
# pve_zfs_create_volumes: []
pve_ceph_enabled: true
pve_ceph_repository_line: "deb http://download.proxmox.com/debian/ceph-quincy bullseye main"
pve_ceph_network: "{{ ceph_network }}"
# pve_ceph_cluster_network: ""
pve_ceph_nodes: "{{ pve_group }}"
pve_ceph_mon_group: "{{ pve_group }}"
pve_ceph_mgr_group: "{{ pve_ceph_mon_group }}"
pve_ceph_mds_group: "{{ pve_group }}"
pve_ceph_osds:
  - device: /dev/nvme0n1
    encrypted: false
pve_ceph_pools:
  - name: pve-ceph
    storage: true
    application: rbd
    rule: replicated_rule
    autoscale_mode: "on"
    pgs: 128
    size: 3
    min-size: 2
# pve_ceph_fs: []
# pve_ceph_crush_rules: []
# pve_ssl_private_key: ""
# pve_ssl_certificate: ""
pve_roles:
  - name: Terraform
    privileges:
      - "Datastore.AllocateSpace"
      - "Datastore.Audit"
      - "Pool.Allocate"
      - "Sys.Audit"
      - "Sys.Console"
      - "Sys.Modify"
      - "VM.Allocate"
      - "VM.Audit"
      - "VM.Clone"
      - "VM.Config.CDROM"
      - "VM.Config.Cloudinit"
      - "VM.Config.CPU"
      - "VM.Config.Disk"
      - "VM.Config.HWType"
      - "VM.Config.Memory"
      - "VM.Config.Network"
      - "VM.Config.Options"
      - "VM.Migrate"
      - "VM.Monitor"
      - "VM.PowerMgmt"
  - name: Packer
    privileges:
      - "VM.Allocate"
      - "VM.Clone"
      - "VM.Config.CDROM"
      - "VM.Config.CPU"
      - "VM.Config.Cloudinit"
      - "VM.Config.Disk"
      - "VM.Config.HWType"
      - "VM.Config.Memory"
      - "VM.Config.Network"
      - "VM.Config.Options"
      - "VM.Monitor"
      - "VM.Audit"
      - "VM.PowerMgmt"
      - "Datastore.AllocateSpace"
      - "Datastore.Allocate"
      - "Datastore.AllocateSpace"
      - "Datastore.AllocateTemplate"
      - "Datastore.Audit"
      - "Sys.Audit"
      - "VM.Console"
pve_acls:
  - path: /
    roles:
      - Administrator
    groups:
      - Admin
  - path: /
    roles:
      - Terraform
    groups:
      - Terraform
  - path: /
    roles:
      - Packer
    groups:
      - Packer
pve_groups:
  - name: Admin
    comment: Admin Group
  - name: Terraform
    comment: Terraform Group
  - name: Packer
    comment: Packer Group
pve_users:
  - name: "{{ root_user }}@pam"
    email: "{{ personal.email }}"
    groups:
      - Admin
    password: "{{ root_pass }}"
  - name: "{{ username }}@pam"
    email: "{{ personal.email }}"
    firstname: "{{ personal.firstname }}"
    lastname: "{{ personal.lastname }}"
    groups:
      - Admin
    password: "{{ ansible_become_pass }}"
  - name: "terraform@pve"
    password: "{{ ansible_become_pass }}"
    groups:
      - Terraform
    comment: "Terraform management user"
  - name: "packer@pve"
    password: "{{ ansible_become_pass }}"
    groups:
      - Packer
    comment: "Packer management user"
pve_storages:
  - name: backups
    type: nfs
    content: ["images", "backup"]
    server: "{{ truenas_ip }}"
    export: /mnt/tank-01/backups/proxmox
pve_datacenter_cfg:
  keyboard: en-us
  language: en
  tag-style:
    ordering: alphabetical
    shape: full
pve_cluster_clustername: "{{ pve_group }}"
pve_cluster_enabled: true
pve_cluster_addr0: "{{ coro_hostname }}"
# pve_cluster_addr1:
pve_manage_hosts_enabled: false
# --interfaces_template: "./templates/pve_interfaces_template.yaml.j2"
# pve_cluster_ha_groups: []
pve_manage_ssh: true

pve_pcie_passthrough_enabled: true
pve_iommu_unsafe_interrupts: true
pve_mediated_devices_enabled: false
pve_pcie_ovmf_enabled: true
pve_pcie_ignore_msrs: false
pve_pcie_report_msrs: true
pve_pci_device_ids:
  - id: "8086:3ea5"
pve_vfio_drivers:
  - name: "i915"
