kind: Secret
ansible_user: ENC[AES256_GCM,data:ogLapg==,iv:1Srx96fuvP1uzY/mrr1EStfH/4uOCie9eh5sDYRqc7E=,tag:ZtKNMVb5X66NVzQH/5FoSQ==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:f9F6nF+f2uyElqP+ANt+,iv:2SuRO8GEy1jSHTmtQNyFEJmEBZL86kzWtkzyR3ZQh48=,tag:2OFBnFf1Q+UOFTHC7lda4g==,type:str]
pve_ip: ENC[AES256_GCM,data:h0ypcDGf7QyIw1qA1Q==,iv:1nS42U5eKBpx6j2rpGTaTYumtpUm1XG1ONp7uwv93U0=,tag:449xJUzz6hU6ixHn/O1kIg==,type:str]
ceph_ip: ENC[AES256_GCM,data:jrpWt1CgG6nLegObA/A=,iv:nSfZPbZ/auMzEaOmwMFsEhCXJ/tckqtFuzYh2X4gpQk=,tag:5reVGjhLUDEe+UJqbtB9Kg==,type:str]
coro_val: ENC[AES256_GCM,data:lMtZGyazhcgij6qPhj2p,iv:XQLXcrMlNxHFcETZ62ATqDlboMUFZwabsanQzimASl4=,tag:2FriiM+opBxaCrrQ/RbCQg==,type:str]
ceph_val_1: ENC[AES256_GCM,data:7o8vhq0a+wxUnK7Xe3je,iv:yTa+PMdcB2pMjbOORXkm9N/tJoyU9gBWWmsOUdgwXBo=,tag:bT84AnMRq1z0aQclkSuknQ==,type:str]
ceph_val_2: ENC[AES256_GCM,data:mqvUlWEQhVc1iU4vm7Dp,iv:QhnqmbtZ4ckZNxC2ihiVHZsx/nNlVdFklPGt9dw5aXY=,tag:dmxco66/ijf8vOwg43vR7Q==,type:str]
pve_hostname: ENC[AES256_GCM,data:gC1TUBYH,iv:OJRcGUWpkAH/XUm8Bwo70h278NmC6oZypfSRUC08Y7g=,tag:Dp3MvmGImSR5M/1lTLkYAA==,type:str]
pve_hostname_under: ENC[AES256_GCM,data:ps58FA4H,iv:iz69SEnquhfVSEItUE+/8lSTwCCr8MOrd/JQ0F6EAng=,tag:nX16ZJMucF00qrvqWuoIxQ==,type:str]
coro_hostname: ENC[AES256_GCM,data:H43CLSYetw==,iv:feiL3iv35J++NmUVo5BUqT9iVjhhNSKMmNPpyuxPAZQ=,tag:1qEntWk+xFwRRrZV2lizGA==,type:str]
passphrase: ENC[AES256_GCM,data:PtN8az4AO2JOnf6zsMrB,iv:DJGRqWLGXdUffqNqLPs2sh/G+pSXAy+6J/7SDzTRP58=,tag:jGP5Sg+KTv9VNcslaMB5xg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:F1CFg5TaOe6Rrp6Q68ss,iv:sZDZsoC1t1XpSqZRiPHmoYgcmmAHjrxcwl1Wxa3y35U=,tag:9ZNVHz/Sgl7bIYWZjFGF3g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-09T01:35:35Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAEsJmR883r450W2qBRWOfOrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDDekyC+Idq11/WwAgEQgDuWFzWypL3XhyT6U++nB8TRuDg3M35omYmMomH7jWjb1MeCqBOkgv9sQKfe4s9akx8Dxwq7Zg+UOu0Mkw==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-09T01:35:35Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgHjd31/n3j+wT2M7A3KvmWGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+iwVR5HEIGLmTYyeAgEQgDtAwGMCOmhHh73adssrvjA0Bc01Ds81HTWKKtw18D6Vvug3PxP7IBu4m/PoiMkmf+WRiJ/WQrC3Mr7h0w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-10T00:56:54Z"
    mac: ENC[AES256_GCM,data:te2ZJxbEBhpVZpUFzDpOLZa2iqWA80iCvoDU0wGyyDAbqGmwCSNRx95Uz+PNYtNoZFlolfCAJZqQU772T3u6//sxuhgWjzol8lRP88bY+XXW0kDHpok+ZVfaNUXYTMuXQ//cKvZQE7jhYi/BNwowDQl+s3OoRBhoeYtUEmTu6M0=,iv:CPT90wwXGE/e70/T6yGMLG8zI/oRIZOmnKAYfEWyzdQ=,tag:GNHRMnzGUNK5B6F6m4e08A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
