---
version: "3"

vars:
  TERRAFORM_DIR: "{{.ROOT_DIR}}/lab/provision/terraform/modules"

tasks:
  init:
    desc: Initialize terraform dependencies
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && tofu init {{.CLI_ARGS}}" \;

  validate:
    desc: Validate the terraform changes
    dir: "{{.TERRAFORM_DIR}}"
    interactive: true
    cmds:
      - find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && tofu validate {{.CLI_ARGS}}" \;

  plan:
    desc: Show the terraform plan
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && tofu plan {{.CLI_ARGS}}" \;

  apply:
    desc: Apply the terraform changes
    dir: "{{.TERRAFORM_DIR}}"
    interactive: true
    cmds:
      - find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && tofu apply {{.CLI_ARGS}}" \;
