kind: Secret
ansible_user: ENC[AES256_GCM,data:jHzlMQ==,iv:BMyZfdXqrvZ03NMoYgCLSOmwIwwbItXwdxK1Zdu4x6E=,tag:byGCMgBUP5+d+GpZniONVA==,type:str]
public_domain: ENC[AES256_GCM,data:zNa44iP25fK85l89pQ==,iv:sdx1BivVW7JsFPQaIUwR6MzpO34Ry4fMJ0AQYwFSll8=,tag:apqMt1SscjURJUuTxUkcyg==,type:str]
gateway: ENC[AES256_GCM,data:VFRm5mUMvRJu,iv:/UUUp4QtZcHf3oWWpZimcS3qGQoHekpU2IjAd1Jtn7M=,tag:cO3ykHz4PDXSZZTjDbaAZg==,type:str]
coro_ip_1: ENC[AES256_GCM,data:ZettDvVYNPySWfs=,iv:PO16yFdqpuTlPUgZd2x1uDKrMBugxtq3DD99WHNoh6c=,tag:JYUev9FUrqNpr+nneigRVQ==,type:str]
coro_ip_2: ENC[AES256_GCM,data:FYF2g0gkP3MP+8g=,iv:Y9WpxQtpB2Y6Q72laLJH6uItXZwHvluLoiGmRF+iqdM=,tag:Itn+fCZ3oC8zkZA9oUPTPA==,type:str]
coro_ip_3: ENC[AES256_GCM,data:XxTeg9i0nzr+Zis=,iv:L5P5LKfWbTvJOyKc5unDUHVpv7xxTNNvWqFlXok/KOw=,tag:LTvky5Fg5dT2Rx0dksJHrA==,type:str]
ceph_ip_1: ENC[AES256_GCM,data:zD6TkFKvYtRlyhc=,iv:6Wv4foNb/rrk1tjqaqRkMt47J1rntFZHa5jZEuq9g3Q=,tag:C0gQwOiFGV024NkGbW/PDQ==,type:str]
ceph_ip_2: ENC[AES256_GCM,data:T37sKlT99dO3w3Y=,iv:FmBBVILxt3m9Fm6/iUyZVFpG7Wdkjuy7LfTBjLOborw=,tag:1vI7jB+PO7paQM3d5xawug==,type:str]
ceph_ip_3: ENC[AES256_GCM,data:eBe0GCJQchQn9mM=,iv:YO2Xxk1bq2UvdE38q3VZych0CPYQcXWssA4cRLtYTFY=,tag:rQGWbSBVZrEJBg3D7aSF/g==,type:str]
pve_ip_1: ENC[AES256_GCM,data:kdyxRGWqHNtlgA==,iv:kuxE5EvbmocvXUtl41lSNUhCYTYS+0JbZ0TQOeQVPdY=,tag:6fnrnZyBGMkkMucc/6pKHw==,type:str]
pve_ip_2: ENC[AES256_GCM,data:dldN8YZH4UA6tw==,iv:CIQz+Qpj/To0FaZsUlArw9D8g++W5NsvFZGLLT+So8I=,tag:QI7Yzx+D9FVmG7WQNZZEKQ==,type:str]
pve_ip_3: ENC[AES256_GCM,data:PEoZ5dDfFLbA2g==,iv:YAiznKaXSvl5O9HqCNbDuM5PhZjSktQXQPYapasSGG4=,tag:sfa08BQ1ZTdjSEuU0J878A==,type:str]
cluster_name: ENC[AES256_GCM,data:56S3YeK/6RDw4Zc=,iv:0O/Cw8KiLf6sOv5u+2RQS+/vvMxLkZ+T3mMBvAaX1AI=,tag:mCvPGuDVShiOxTb1whoJyw==,type:str]
initialized_coro_domain: ENC[AES256_GCM,data:8KEOmSIU5LWOh6vrbwZwBfmDQ0ln,iv:rRdC4tmaOmFTItJibRl+tY/KBW4Ltwav2uiogRKMrSc=,tag:rfEv9rfB1jkPx5v/p/MakA==,type:str]
mgmt_user: ENC[AES256_GCM,data:rhj6jx9uQPPF,iv:E20O3Fk2NVGE+UALTDewPHFM23w5umkJSOL1FdrYjVA=,tag:zyEUW/tYgzB/r7X6Pb1r2g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-08T14:26:33Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAFybOrMlfsYqQJ+V+8IyeykAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMs/2guc/3FD6yQYwFAgEQgDvhXZpASpjbjQ8LKcdhPSoYKh1KL+vDxbnDFCIPac2lkBnaKfI8T/nUhTtZDoGA9QdOto4EqZla9goW8Q==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-08T14:26:33Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgE3+2VJT30ULTBS4nKMqP1QAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhjLnezi1jMR4mumzAgEQgDvAHO2EPwqnLIJs4mBsLlxZElIRHWwAiDNImDcq9Nb1btZOwN609rxZhqu4TByHdMLSmMZun5we3CmSRg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T21:59:35Z"
    mac: ENC[AES256_GCM,data:UbKnXFqzv+0zRHfYhE+b3avDHA7kl9ZoCXwglylenJ2mAKdATzEKhykulztcaL/uZO7kUCGkxF0pcYSlN2epQWjWhcsR3KiG1o0OfE0Y2liinJAn8Nj2sTVsRnm2ZRkJV0Jv7vVBZQynLoHOw+s11aHtQsSGQjqnyFhytWe7CBY=,iv:yaa9+UI+2zXSIleQorlzGSJy/M/XoeUTj3kQznQAWPk=,tag:e2MBH2qpKXs7DaQQAllwlw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
