apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    discord-webhook: ENC[AES256_GCM,data:G+/W7xlqKP7kl8P3DtxDpqdEcMrxBhfJVFfth1Mk5BG3Gx65T450H0bduXKn2+3bSY4BOCR2pkPXE6kqXrUPvnAMLuF6hdOeGIleIdknE4XrSjmylpsCXBAgzmLuoVPHnlAfMMXOe8UTnHzXpSXCY4HORmN3jrRzyw==,iv:yRgq3bs5U/j7XlbimNdngURiZJwtI7m9E0sq2338PqI=,tag:G+73/iublj5Kuyzmo5QYJA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:869935076354:key/4a38975b-065e-4cbc-b0d7-b6067418b38f
          created_at: "2024-10-11T17:12:21Z"
          enc: AQICAHjEXmBmWhTFPoI6sZz9xRf37CwVV0xZ3J51JBykh8WU6gF7oxqtTki4nIPWVEuyYNYBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfqVktRJK4wRM1eXXAgEQgDsdfM/HIRbZUrPVVVpsZqE1yGN9KVHVfZ+qr9xUURXSkq7GPW2zEwGRXcI4aBa7DAu+Q+ciCzy0hJxvhA==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:869935076354:key/6baaa7c8-967a-4fc5-9923-c0a938edfcf4
          created_at: "2024-10-11T17:12:21Z"
          enc: AQICAHi4b7+9FI+voNyOntA45UFh2ygAmwOs2iw6TIerHZXspAFWQXHMEO4S6bznVpaMAyxAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQML4Ji668ga5scECqyAgEQgDuobH2xGffkSVpUFzwvFxNFHwumt6De2lD4JjHwYELIbhtWqBxKuBSFFca3jDbXVYpSYompWLkGRuWF5A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-29T00:08:04Z"
    mac: ENC[AES256_GCM,data:1CY/sfi5dXCxHBHxf88L5NXGknjSlKNpfJ6NGPgLVbQTKy4W+xljt2W+qmaWUuI2rRsgTZMLdh3HypB4aSsqp5Zcs6zat0b3KSPc9h4gNBPSSTrBm8BQPdxa4lut1PBAnUbaQG/vSAbT3MgdH9mNTPef3FxzFanxsqMkILNzFLc=,iv:EVgeLghfBHNVDec+S62p5Esm+zRmMM0lyW0nG7xpwZQ=,tag:6G42bLCxRyxSU46l+FfXRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
