kind: Secret
ansible_user: ENC[AES256_GCM,data:bVyU9g==,iv:EbgVtqGtc1dv56NRZkT8slfDNxdmtiOyNEN2LmNaVco=,tag:ZmKodt1bX+AARnLwWiTczg==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:TGj6w09PlAm6AQ7WlLEp,iv:4gE5+01tzal2FrgL/E7EkkBF48nlTMxQ3glHQJ8Hpeo=,tag:VpRWdyzIbb+9capVVLD0nA==,type:str]
public_domain: ENC[AES256_GCM,data:/defKvdsOL4=,iv:sKzUs2Y+8Sa3CHJ/QZCG9D0gm44Fcj4sUepFyk/zV5k=,tag:lq4gG1KSycoju9AYmEXfSw==,type:str]
ansible_connection: ENC[AES256_GCM,data:D1cOY4XMc0dLYttZGE0d83POt3v7dwPg2INiMms=,iv:tLkw+AYd8zHFF/We6FViF+YeHBD7p5kAPq48rbUbo0o=,tag:PdA3vEVHpE+665+TlPFIWg==,type:str]
ansible_network_os: ENC[AES256_GCM,data:/ZklRhtfRxsulqEGpg==,iv:7xIW381psbKechMoxJvZvvs7sZryzcbG8hFplkv9y+g=,tag:t1TgK526G4AnFLKCQ6zMtA==,type:str]
ansible_become: ENC[AES256_GCM,data:AqKjNw==,iv:F1WdouWcDR5Ef8pQuZLaQflwAmGPe4cK0FCrKv/pzuU=,tag:bK4jllw6RDRopmulFJDJFw==,type:bool]
ansible_become_method: ENC[AES256_GCM,data:5+nluiv3,iv:LR1i6lIy3xJiQs/5sG7D9MTrBkDY+FH6IV8NLA8ZGtA=,tag:HM2JVTXSUeRKrjgiZtPLHg==,type:str]
ansible_become_password: ENC[AES256_GCM,data:A3H/y6HtLGl5pR+SsUaO,iv:grYOT4WNzcPF+Va2K6T+6sEn3AoYIvn+HC0PgOTpW6k=,tag:TbMgSl/zgGPK1zUdPVAj5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzRrSFNmdmprNSt3MjZy
            d3E3M0FkTjZIa1JGa1hyZW1zUSthd0Q1cDNBCjBodmx3ZTN4UnNabldkMjJBODF2
            ZUlwV1pySkcrS2xQSVN3VklSTzZGNnMKLS0tIENqOHFISmFKYnZSTjlRL1p4NUZ4
            QU9wK0dhc3hYaWltbkFrcEFITnFsYlkKViIkbtcvoTgcyqtUP+2POE+7SfMdb1xK
            mSxQI7yP70cA79cLF1wWRjamYltRFZZU4NHmbi7esMLSNJr0VLieaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T16:19:32Z"
    mac: ENC[AES256_GCM,data:3PJAOTzKxlUhR4T7lxMS7AbQnAmaBuF3vSANp67wuuYteMR6J6QTpdKuek+EyXvjJVJFF3yob/7Dqp8PDeYn78eM927y+B2iL15yFsDTOCZGwg/Zr6Pz/oczB40wDe3k1+Pt3hvmvRrSL83wzPZy8Vuxno26zKrmixR56nmuttA=,iv:5+EYfqi5UIEoUZQkSs65vg2JKyh5w7aWjNq2R5uMzVA=,tag:PtJJ+oiGJaYWKyT3m9LBqw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
