---
- hosts:
    - opnsense
  gather_facts: false
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
        - name: run show version on the routers
          ansible.builtin.ping:
