kind: Secret
ansible_user: ENC[AES256_GCM,data:OnCjRw==,iv:4FPKkoFKDBBJJZAf+emqyfPdmMgO4SF8UkhUdEqCRw0=,tag:ZsmKm1nI1nKYxZtXIM9IzA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XV4y9Q==,iv:QKRML1z79B7JVFP0Cwz69rSpT9WG4yqc+qYxij7LMas=,tag:AG+hZwunA1rc3vmXltWB2A==,type:str]
public_domain: ENC[AES256_GCM,data:Tt7LO1H8v5g=,iv:MhyNxTYQFC4rsETCKKD+YGuga2UFF3EauwO4noattE4=,tag:WBn4/p3ATMMFa8h8MXjAeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK0ZDQ013b0hMeWhnYnNK
            ckVPa3ZYMWxmK3dZLzhzQ0YvSGRMVVpRWkRvCmtRVDhkK3lqWWRtMWlkL3I3TTdO
            OE9nbU9VVVJGb05LUTVmR0FoMDZFcWMKLS0tIGpHVWR5Qm53S2dVdmlheUsxYUUx
            OW81TWtGVHVvaTV1L2M5ZDhRR0h0cTgKNRzvCL8ioXGKfBkUQHufhalreZrJxftl
            2QZXyFWNpDf9Zfgu7FAAoqpmZ/EArfvNl32hc+2tx5x07ccM8QapUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T17:07:45Z"
    mac: ENC[AES256_GCM,data:Fsuv/Y71wUzuVxLPQv5ny8SIVfq6xdlU7HxJmNc5tQ0kahmaMP3U1rrwtSMvsljQI/EfoqX0Gi3A9NgDZdv/KUg39DAXL9nnC4o9kv/mVLc7h3dZujRDkb0CXO2LJEdVKJWI4kbZf7f8j2HiAKzvDx5TF6igZ3qo8ls/6yzPV/E=,iv:lLaRA85d2kos89MOK1IELIThQPu5xOKCVD70aDsbbHI=,tag:ro0D9p/3+cKulsiVXd+0Pw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
