kind: Secret
ansible_user: ENC[AES256_GCM,data:ns5cLQ==,iv:Skm6GmbkHoF3ERo/6J41JHQUG154O0b2qFwh/ezCvBc=,tag:Og3uA+HoTR1IG9JYXQwNpg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Q5aHW7g8BcCsaim37KmR,iv:9mm7GmbSH4CnNc6p05rJVvQcGPCAZEOvkN+NOmMbf5E=,tag:uxzSjqtJ1pvXkmwFyp+oOw==,type:str]
public_domain: ENC[AES256_GCM,data:CMZT7UZrPco=,iv:e5MvJCKivUYWDOmG6pd4oJL+q9RfAGqTGkS3HrjTt+U=,tag:7ABorOuSGYcwb2eCSmPsNw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2023-04-10T21:10:24Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAHaOSPpCKPmUI5rqE3ANqm3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9IDPCnqJrvJ8ThnmAgEQgDsfM1qyZLNUiW2AAocIS/rRqxwlQd62VWVcCS/oD62GuS1ena7dDQOBrrskxY/COC+mWWjKpgksGoobJg==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2023-04-10T21:10:24Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgGxvWkaoTRGfylvgs2xYANlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyqMDCtxPR74eBmnXAgEQgDuyB/4VZ9tVMeVy/tGfxfTwgXfwV6vhYk51eAFoBJ5M73EH+UQsYe4ojfRQXb5eFIAAkM6wYGFe4UCUhw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-10T21:35:36Z"
    mac: ENC[AES256_GCM,data:0OZP9vZLMRAkVPA3fhJz8GPfgt5YHEMAECVdlTGh836yOuTonwlFOJrx7dbuGfQ7PK9JzHhinTN343bqlqlJXGdoHCy4oogtP+qk/6jtBPITPQfGSwTTQdr06utsJTIGYjWdCI1KwtErU3S+7XrILAZuzlOpZHFOSFHm/w4K6Fc=,iv:3W3GzVWoZgPSDnk5ZzQnEZXcnvrs8Njmn0GrBIRVz1w=,tag:SNe+Craq+a9wkRR+xnbYSw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
