kind: Secret
ansible_become: ENC[AES256_GCM,data:W9FVkA==,iv:pFCzvg5SHQdfep3QNXUv2CvGCnyGgOgLVZ82vWBpgMM=,tag:yxfDsa6GQS5L4EhMIqz23g==,type:bool]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-08T17:07:48Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAH+4UdU6NlRXZcDRk9mha/AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgONgg4KS6l+ZZM3EAgEQgDtoiLhn8ao7o95qnAkfE7NHg3n4WaMBxYHQvw7x1c8pjfRQf00gvOCvlz5dbm/wYAA71aI4w1Nkuq2wVg==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-08T17:07:48Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgF1GiR1aE4eh927JTyGyou0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0mip+HNvujG0uUZaAgEQgDsMwyalUcxoAfwgfMFUGebA4C5D++fwsKsmj4L/uUSW8YkaDys/ulnomRpJdqhW05Jno5cbTXnBFUooJw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-10T12:52:44Z"
    mac: ENC[AES256_GCM,data:XCBtWJuELvF/RLAQ9l3Lwpt/KKRoXl2bbp23jQ7meUxG9eDps9zggUZSR7gvbq9K2moWg2GzV4kXX/M3o3u1RqQWgzE9jWamlTr0jsduahB95CdzOu5tcFZxCZdOFZtN7+ChaVKVwCxmU58Rl+aiOWviILWx1Xrvk/styOu4qxw=,iv:PzK3NsLK3dhmObQ6pKPhMJ7c0V/VJeTPg0BCAHuLTcY=,tag:tsOhJ+CpCUy68r1q5i9G/A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
