---
- hosts:
    - mgmt
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - block:
      - name: Pausing for 2 seconds...
        ansible.builtin.pause:
          seconds: 2

  tasks:
    - block:
      - name: Create base Proxmox SSH directory
        file:
          path: /home/{{ ansible_user }}/.ssh/proxmox_keystore
          state: directory
      - name: Create sub PVE SSH Key-Pair directories
        file:
          path: /home/{{ ansible_user }}/.ssh/proxmox_keystore/{{ hostvars[item].directory }}
          state: directory
        with_items:
          - "{{ groups.pve }}"
      - name: Generate SSH Key for PVE Nodes
        community.crypto.openssh_keypair:
          path: "/home/{{ ansible_user }}/.ssh/proxmox_keystore/{{ hostvars[item].directory }}/{{ hostvars[item].key_name }}"
          type: ed25519
          unsafe_writes: false
          state: present
          regenerate: partial_idempotence
          passphrase: "{{ hostvars[item].passphrase }}"
          backend: cryptography
        with_items:
          - "{{ groups.pve }}"
      - name: Transfer public keys to PVE hosts
        delegate_to: "{{ item }}"
        authorized_key:
          user: "{{ hostvars[item].user }}"
          key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/proxmox_keystore/{{ hostvars[item].directory }}/{{ hostvars[item].key_name }}.pub') }}"
          state: present
        with_items:
          - "{{ groups.pve }}"
