---
- hosts:
    - mgmt
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - block:
        - name: Pausing for 2 seconds...
          ansible.builtin.pause:
            seconds: 2

  roles:
    - config.mgmt
