apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:OLfLzVAyglhQer4UMTy1hkRkvVobdeBd/vE8L0S4/XDVZJk8sw==,iv:/gpBSrNzot2Tq9YN++BF/Wmm2iuj7ksRHOdwr4QKQCQ=,tag:gIZoUsy5WR5WL71reJSNcQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-07-28T14:03:26Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAE+Trq91W39vOx2Qhnc4IBaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwS5l1Lql282QtI2CAgEQgDsjrIL0NjhomKkR3I3zaiKPOLTqiHECQlJdo6FcJrnalIk0cHNF6gbW/12FUk+pFSrwrQmVSkV2jujh0Q==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-07-28T14:03:26Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgHcLuN9UzRrImE8YT3tp7AiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+kijfQ2yYLboRwPtAgEQgDsBMafZu16gSZpmo0OECWjaSBnCEXX1/3hdalSgq8ljbPRcuNu1+2phmRWriSsKYDxX8dmJ6OGMLcv+Gw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T14:05:48Z"
    mac: ENC[AES256_GCM,data:pKv4gYtMmRjn2uEB8M+JmbQ2Yn2kLqKT37cRxDd+SG7tU2cTr9dDWXVH9jHQ1n4m+hl18ExJTvQsLVf1c4qvshCoFZe2HIZUFKYvmTkgzMymw081W0gtuV/MBrLbLea2mNet39DPgUdp3yIQp3pmW+a4EKrC/L7Z1AnkA/KSlC4=,iv:7bmUp3ST/DcamuN2CtXnfpjtwGT/cC5/OaK2i2ATzx8=,tag:TvHPbT2zLVJZfLd2pBQbGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
