kind: Secret
public_domain: ENC[AES256_GCM,data:XMWEx5sqJSXDWy4pvg==,iv:+FhI8VRYvPRtv6U5f79g/1m4yRyY57BIBVvIaZvBqfA=,tag:Ds0MayHuep4se64jkMdK+A==,type:str]
ansible_become_method: ENC[AES256_GCM,data:7KT5PA==,iv:ksVBTpzmOL6gc07YoAixehDBEqPlNkySjzRYWJerjJ0=,tag:8hB0sn1BpPBey/BqCODavQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-09-10T17:38:35Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAFShecUfCkpOdRb2pYnRCF0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPrSKY6VliL3QXnH7AgEQgDt1J8M3Oustk1vW5iXrqgGge1O7E4C+KUnYpK1yVQsHxFwxMC853YUo2WRMZdTSzcsnC/FRFfrBrsqOqQ==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-09-10T17:38:35Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgE/Hvj+AUmLlsE3XbT+xN89AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5LKXdF00bePb6SONAgEQgDvqfxDKkMP708+JEbPjuHJXO3+uhOFSD0wZAiwplWf7vwjvQzJLQoDg+4taLUlWIt2vlEaJ71DOLqm/Jw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-10T17:38:48Z"
    mac: ENC[AES256_GCM,data:75UznR8+d1gRWsj1ddT6suZys6GzZHT/jsGx1SKM6EJHdHp4Fj1Xq4XRLF29djcjX4bNxYr4BPxAI4FI0IdQmE2EDC5i8PsrN7HrqLhDwhoj5R9xYRaA32o3e4KMN+CfCDtFEpSD+x5OjaTtIz+tCloSXW8Jxm+sd9w9pin68iY=,iv:9guUtsohCqmdyoUM7/edh1ZYsvft5e2Ag92fkyKYJ7g=,tag:ESJhg0sScb+5mwvWnoahww==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
