---
- hosts:
    - k3s-cluster
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - role: geerlingguy.ntp
    - role: hifis.unattended_upgrades
    # - role: Oefenweb.fail2ban
    - role: xanmanning.k3s
    - role: geerlingguy.helm

  tasks:
    - block:
        - name: Update apt repository and cache
          apt:
            update_cache: true
            force_apt_get: true
            cache_valid_time: 3600
        - name: Upgrade all packages
          apt:
            upgrade: dist
            force_apt_get: true

    - block:
        - name: Install apt packages
          ansible.builtin.apt:
            name: "{{ item.name }}"
            state: "{{ item.state }}"
          with_items: "{{ apt_packages }}"

        # https://docs.crowdsec.net/docs/v1.2/getting_started/install_crowdsec/
        # https://packagecloud.io/crowdsec/crowdsec/install#manual-deb
        # - name: Install dependencies
        #   apt:
        #     name:
        #       - apt-transport-https
        #       - gnupg

        # - name: Add an apt signing key
        #   apt_key:
        #     url: https://packagecloud.io/crowdsec/crowdsec/gpgkey

        # - name: Add apt repo
        #   apt_repository:
        #     repo: deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} main
        #     update_cache: true

        # - name: Install package
        #   apt:
        #     name:
        #       - crowdsec

    #     - name: Modify node hosts file to use correct hostname
    #       ansible.builtin.template:
    #         src: "hosts.yaml.j2"
    #         dest: /etc/hosts
    #         mode: "0644"

    #     - name: Reboot all hosts after renaming
    #       ansible.builtin.reboot:

    # - block:
    #     - name: Run proxmox role
    #       ansible.builtin.include_role:
    #         name: xanmanning.k3s
