kind: Secret
ansible_user: ENC[AES256_GCM,data:vPD1BqHaLb3K,iv:XT7NKjNQ68563drIykVXqCUQ8rd92QG1BOab0lGvKzg=,tag:3oBBMlwxrlVJ+61rzonuQA==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:f9F6nF+f2uyElqP+ANt+,iv:2SuRO8GEy1jSHTmtQNyFEJmEBZL86kzWtkzyR3ZQh48=,tag:2OFBnFf1Q+UOFTHC7lda4g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:F1CFg5TaOe6Rrp6Q68ss,iv:sZDZsoC1t1XpSqZRiPHmoYgcmmAHjrxcwl1Wxa3y35U=,tag:9ZNVHz/Sgl7bIYWZjFGF3g==,type:str]
root_pass: ENC[AES256_GCM,data:4LM5wws3/iZzRNh5ek9S,iv:CfNehesgY0nNMSFK5NUxmZbELHQjbn12ACVItzl2mfU=,tag:v4eWBZll41+gqEDxHfxqog==,type:str]
pve_ip: ENC[AES256_GCM,data:X7gya+Ef8KIAAY0=,iv:LbBE+KunHNLtu0dZsvA7UfLs1C6KL5C+kAb68dIm+as=,tag:k2D9SNi9PZPwAxzrbrUSbw==,type:str]
osd_id: ENC[AES256_GCM,data:dA==,iv:eYWtQW+YjYKh1yGcxcHgWm8W0V13kSD+baCAo81MAco=,tag:gdXikUv5UwYmlyOiKrX/uw==,type:int]
hostname: ENC[AES256_GCM,data:Pm5jXb+2ocs=,iv:NWgmHe+qSlHiQa6IbowUwLYvMwXnZCvix25otJYqMqQ=,tag:4F3FZV/aUDlVnqsc3T4m6g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-09T01:35:35Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAEsJmR883r450W2qBRWOfOrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDDekyC+Idq11/WwAgEQgDuWFzWypL3XhyT6U++nB8TRuDg3M35omYmMomH7jWjb1MeCqBOkgv9sQKfe4s9akx8Dxwq7Zg+UOu0Mkw==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-09T01:35:35Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgHjd31/n3j+wT2M7A3KvmWGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+iwVR5HEIGLmTYyeAgEQgDtAwGMCOmhHh73adssrvjA0Bc01Ds81HTWKKtw18D6Vvug3PxP7IBu4m/PoiMkmf+WRiJ/WQrC3Mr7h0w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-19T03:12:22Z"
    mac: ENC[AES256_GCM,data:QE2sLr4KMJZJ4YpbaQt/g+lPdzDoNs2MQ5YAfyT4X8YFXQ3RM7PYDZAmTrZFdEAT7oLe7oJX7ORMhJDnKWIMF/jlYJYb4JeFHKTSk/XHtZdgbKUDKi84t0/kAU3QYIM3E8csTVfR+OGNbZXWcMXM7Itv4AyFzrmgSCM0o2VuFkI=,iv:Xp/HCsYVQKicYjuo61J4PWOpNp5EZ1swq2oXpPWrjIE=,tag:dr4/NOUUFKO8HKOihea3EQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
