---
- hosts: pve
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - role: geerlingguy.ntp
      ntp_manage_config: true
      npm_servers:
        - 2.pfsense.pool.ntp.org

  tasks:
    - block:
        - name: Create Terraform User
          ansible.builtin.user:
            name: terraform
            password: "{{ ansible_become_pass | password_hash('sha512') }}"
        - name: Create Packer User
          ansible.builtin.user:
            name: packer
            password: "{{ ansible_become_pass | password_hash('sha512') }}"
    - block:
        - name: Install openvswitch-switch packages
          ansible.builtin.apt:
            name: openvswitch-switch
            state: present
        - name: Modify network interface definitions on pve hosts
          ansible.builtin.template:
            src: "pve_interfaces_template.yaml.j2"
            dest: /etc/network/interfaces
            mode: "0644"
        - name: Update /etc/hosts file to contain all valid ip addresses
          ansible.builtin.template:
            src: pve_hosts_template.yaml.j2
            dest: /etc/hosts
            mode: "0644"

- hosts: pve
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: lae.proxmox
