---
- hosts: pve
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - role: geerlingguy.ntp
      ntp_manage_config: true
      npm_servers:
        - 2.pfsense.pool.ntp.org

- hosts: pve
  gather_facts: true
  any_errors_fatal: true
  serial: 1

  tasks:
    - block:
      - name: Install openvswitch-switch packages
        ansible.builtin.apt:
          name: openvswitch-switch
          state: present
      - name: Modify network interface definitions on pve hosts
        ansible.builtin.template:
          src: "pve_interfaces_template.yaml.j2"
          dest: /etc/network/interfaces
          backup: no
      - name: Update /etc/hosts file to contain all valid ip addresses
        ansible.builtin.template:
          src: pve_hosts_template.yaml.j2
          dest: /etc/hosts
          backup: no

- hosts: pve
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: lae.proxmox
