---
- hosts:
    - pve
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  
  roles:
    - pve-node-config
