- hosts:
    - pve-join
  become: false
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
      - name: Join existing Proxmox cluster using separate network link address
        ansible.builtin.command: 
          cmd: "pvecm add {{ initialized_coro_domain }} --link0 {{ coro_hostname }} --use_ssh true"