---
- hosts:
    - pve
  become: False
  gather_facts: True
  any_errors_fatal: True

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
      - name: Modify package repositories to use non-production
        blockinfile:
          dest: /etc/apt/sources.list
          block: |
            # PVE pve-no-subscription repository provided by proxmox.com,
            # NOT recommended for production use
            deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
          backup: False
    - block:
      - name: Update apt repository and cache
        apt:
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
      - name: Upgrade all packages
        apt:
          upgrade: dist
          force_apt_get: yes
      - name: Check if reboot is required
        register: reboot_required_file
        stat:
          path: /var/run/reboot-required
          get_md5: no
      - name: Reboot server if kernel updated
        reboot:
          msg: "Reboot initiated by Ansible for kernel updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
        when: reboot_required_file.stat.exists