---
- block:
  - name: Update apt repository and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  - name: Upgrade all packages
    apt:
      upgrade: dist
      force_apt_get: yes
  - name: Check if reboot is required
    register: reboot_required_file
    stat:
      path: /var/run/reboot-required
      get_md5: no
  - name: Reboot server if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists

- block:
  - name: Install sshpass package using apt
    ansible.builtin.apt:
      name: sshpass
      state: present
  - name: Install python3-jmespath package using apt
    ansible.builtin.apt:
      name: python3-jmespath
      state: present
  - name: Install python3-pip
    ansible.builtin.apt:
      name: python3-pip
      state: present
  - name: Install virtualenv
    ansible.builtin.pip:
      name: virtualenv
      state: present

- block:
  - name: Install pre-commit
    ansible.builtin.pip:
      name: pre-commit
      state: present
  - name: Install pre-commit git hook scripts
    ansible.builtin.command:
      cmd: pre-commit install

- block:
  - name: Install the latest version of awscli
    ansible.builtin.package:
      name:
        - awscli
      state: latest
  - name: Modify AWS Configuration File
    blockinfile:
      dest: /home/{{ ansible_user }}/.aws/config
      block: |
        [default]
        region = {{ AWS.AWS_REGION }}
        output = json
      backup: false
  - name: Modify AWS Credentials File
    blockinfile:
      dest: /home/{{ ansible_user }}/.aws/credentials
      block: |
        [default]
        aws_access_key_id = {{ AWS.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = {{ AWS.AWS_SECRET_ACCESS_KEY }}
      backup: false

- block:
  - name: Install Mozilla SOPS and Modify Permissions
    get_url:
      url: "https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux"
      dest: /usr/local/bin/sops
      mode: +x

- block:
  - name: Modify Git Configuration File
    blockinfile:
      dest: /home/{{ ansible_user }}/.gitconfig
      block: |
        [core]
          editor = nano
        [diff "sopsdiffer"]
          textconv = sops -d --config /dev/null
        [user]
          email = {{ personal.personal_email }}
          name = {{ personal.personal_name }}
      backup: false

- block:
  - name: Add Hashicorp GPG Key to trusted Keystore
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
  - name: Add the Hashicorop Linux repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
      state: present
  - name: Update apt repository
    apt:
      force_apt_get: yes
  - name: Install packer to system
    package:
      name: packer
      state: present
  - name: Install vagrant to system
    package:
      name: vagrant
      state: present
