kind: Secret
ansible_user: ENC[AES256_GCM,data:9S6Akg==,iv:jLXFG7/m+VQKGvQ0sif5RNbqXVm1vm+vqaW7IYKOQh8=,tag:bqPcrCQoUP0+My6YHGgyQg==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:SwEEnUlJ84QLhBZkeytC,iv:L7miKgBzXcFCq5kxLFLl5gEnRwIi6gJSU4DOIGH601c=,tag:93qNVcykK/UAgfLm5jurgw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:fLweHnkr+xXS2/lZyni8,iv:caYQoUibCHLW8/NllUwtWieCVHpRW/6piW64i9Jutpg=,tag:c1Xg9U1BBBKKmO0gxXhNmw==,type:str]
hostname: ENC[AES256_GCM,data:qBxFco8svrde9OoMBA==,iv:nSYFytS4aNs2YXb+LW8rHTdUVwJnhxAJCxxCCOAGkQ4=,tag:GG+PLtN5lAXSrRCnp3KTsg==,type:str]
k3s_ip: ENC[AES256_GCM,data:T3BONQmCdOXG/M8=,iv:jMeNuzUhUbL6uBggKPNKCWJx8KR5309zwvyfGlTCDQg=,tag:1F9/7gUK9+gn4K62UQ93dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSU5rdWNPR0hEcC9uUEtC
            Z0xiWjl0bG1UY0QrdHpkTFB5Rm5USFRNZEVVCnAyYVRSeWRzZkpyQXh2SHYxT2lY
            aGxDa0htQkxBdFpjZ2VDa0tVUldJeFEKLS0tIHRvamVyM0s0dThDVFdldUJIbWhT
            MXpZSHlZZHpyeEVyK2ZXZGxNMlVhQ3MKN9sq18FCv9nBY4bLOdPCcPfIul4NpzF3
            CwKoh5fcLAXxYAdWAvHHFmSdh2VL3rOyFEo/TA3/5LdzKF7xKEXmWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:08:00Z"
    mac: ENC[AES256_GCM,data:AE3GK6ncV8p+j8Ajc7MioeOu196qLLoGnbf1KC0qqxHh0kIIR+sFYbgyRXcWHVFsyAJmGG/4KfWtiH6+iZ0Fjjia6xJU6pAFIIeCgNM2Km7xfBYO8s7hAGUukqPPa85SsXDuWzzUgjlrAva1HIQPS12URzrpJHpmRANbDtqGCpk=,iv:mvGscDfxUUMj8dvnGOznN+XGvLt+usWLNpLX3dcvDEg=,tag:jA/FyfHXdSfPnC1hZ5cXVg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
