kind: Secret
ansible_user: ENC[AES256_GCM,data:OXnOdA==,iv:29JonlNgz4OchfN6Wez8vJh9za1Pg9kFSoO+VMWZ7DE=,tag:VYYzThbDbGXuNKcRunqnug==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:6fwgAiI8lDIt49BP7Ze0,iv:Z41+twHs+39l+dhtQfDwsR01T+TA0YmGzTpueyXSurw=,tag:XFzZybbqHSscRPpIxO8T+w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:R5FDfZ/Hx7x1o1vHTi7V,iv:IOuItyoa81I6eKCDgK9DlLvT+Ogv99rZHAdyIYKDSGk=,tag:Bnnw7Ul6XYMSpiwuD1tZzw==,type:str]
hostname: ENC[AES256_GCM,data:+GPmgcswnc/Y5oRl1A==,iv:FcQNAC4Rle4Rt7WR3HvFcHrcAOlnccvs2cNdFsNScCU=,tag:WzhjPc/MDUIFNDvAsMBb9w==,type:str]
k3s_ip: ENC[AES256_GCM,data:y2Nu2zi3bpdBQFE=,iv:9nyIPSQc2nnXyxUPT8WAWGEe/EA6y0aqiXVwIMiK9sE=,tag:ZjdZhKEy0DJjm2WiNxKJgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y0dkWGZsRDAwd1VyVk11
            OUlqZ1BHWG9sbTNydFhhS0hWWktkNGdneTNrCk9oazk3RTduTWVKYmZtaG1ieXNL
            bkhCT1ZPeFp0bERKdm1WenNsVnFRNEUKLS0tIEhBTGgzbGNDRGZFRnAyenhETStp
            UjNzR2hRMHpYUW1tNURqeDVVMjYyQjAKSjxdrHKjqn3Dz/J3kof51Wa0K0PNzZZH
            v3gpmBceuSbKQ/TMbm9X/0g3WPz9EiaAhyZhsNru3wP6GrIexUFbHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:08:00Z"
    mac: ENC[AES256_GCM,data:7mzuvO28JD1zLRvOhaEgzhF1TRxpO8RVMxmnBpzrS4D5yVr32wRWZ0YjoIV3xd5OJ8MsXGswHnZpNoCip5P+GHdBShjZRMawQRd2cqVK3tB7yR5vYgVjQ57ksFMrAcgQOiQbxf8277VGlErgR0EKM5vjXf3Qs/ewIeHTrwpTznY=,iv:VFzW9VL/dJywlzWsY18IUTldRnLijPtjiwTsXZTRzCs=,tag:ClN8FLHme7UYXD1qzwSAtg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
