---
- hosts:
    - mgmt
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - block:
        - name: Pausing for 2 seconds...
          ansible.builtin.pause:
            seconds: 2

  tasks:
    - block:
        - name: Create SSH keys
          community.crypto.openssh_keypair:
            path: "/home/deloa6133/.ssh/ca_key"
            type: "ed25519"
            force: false
            comment: "SSH Certificate Authority"
            state: present
