---
- name: Initial management node setup and configuration
  hosts:
    - mgmt
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    # - role: andrewrothstein.sops
    - role: buluma.git
    - role: buluma.hashicorp

  tasks:
    - block:
        - name: Update apt repository and cache
          apt:
            update_cache: true
            force_apt_get: true
            cache_valid_time: 3600
        - name: Upgrade all packages
          apt:
            upgrade: dist
            force_apt_get: true
        - name: Check if reboot is required
          register: reboot_required_file
          stat:
            path: /var/run/reboot-required
            get_md5: false
        - name: Output reboot request if reboot is required
          ansible.builtin.debug:
            msg: "Reboot is required. Please restart the Management Node(s)."
          when: reboot_required_file.stat.exists

    - block:
        - name: Install apt packages
          ansible.builtin.apt:
            name: "{{ item.name }}"
            state: "{{ item.state }}"
          with_items: "{{ apt_packages }}"
        - name: Install pip packages
          ansible.builtin.pip:
            name: "{{ item.name }}"
            state: "{{ item.state }}"
          with_items: "{{ pip_packages }}"

    - block:
        - name: Modify gitconfig
          ansible.builtin.template:
            dest: /home/{{ ansible_user }}/.gitconfig
            src: .gitconfig.j2
            mode: "0644"

#   - block:
#       - name: Install Mozilla SOPS and Modify Permissions
#         get_url:
#           url: "https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux"
#           dest: /usr/local/bin/sops
#           mode: +x
