---
version: "3"

vars:
  MANAGEMENT_RESOURCES_DIR: '{{.ROOT_DIR}}/.taskfiles/management/resources'
  ANSIBLE_DIR: '{{.ROOT_DIR}}/.taskfiles/ansible'

tasks:

  bootstrap:
    desc: Initialize local managment sever node
    cmds:
      - task: init-aws
      - task: ansible:install
      - task: init-sops

  init-aws:
    desc: Install and Configure AWS CLI v2 as well as credentials
    cmds:
      - bash {{.MANAGEMENT_RESOURCES_DIR}}/scripts/install_aws.sh

  # bootstrap:
  #   desc: Initialize local management server node
  #   dir: "{{.ANSIBLE_MGMT_DIR}}"
  #   cmds:
  #     - task: aws-init
  #     - task: sops-init
  #     - task: ansible:install
  #     - task: ansible:init
  #     - "ansible-playbook playbooks/mgmt-setup.yml"
