---
version: "3"

vars:
  PACKER_DIR: "{{.ROOT_DIR}}/lab/provision/packer"

tasks:
  init:
    desc: Format packer files
    dir: "{{.PACKER_DIR}}"
    cmds:
      - "packer fmt ."

  update:
    desc: Validate packer files
    dir: "{{.PACKER_DIR}}"
    cmds:
      - "packer validate ."
