---
- hosts:
    - pikvm
  become: false
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - block:
        - name: Pausing for 2 seconds...
          ansible.builtin.pause:
            seconds: 2

  tasks:
    - block:
        - name: Unlock files for write
          ansible.builtin.command:
            cmd: "mount -o remount,rw /"

        - name: Update /etc/kvmd/tc358743-edid.hex file for Intel NUC Compatibility
          ansible.builtin.template:
            src: "tc358743-edid.hex.yaml.j2"
            dest: /etc/kvmd/tc358743-edid.hex
            mode: "0644"

        # - name: Modify ssh default user and access accounts
        #   ansible.builtin.user:
        #     name: "{{ item.name }}"
        #     password: "{{ item.updated_password }}"
        #   with_items: "{{ ssh_users }}"

        # - name: Modify web gui default user and access accounts
        #   ansible.builtin.user:
        #     name: "{{ item.name }}"
        #     password: "{{ item.updated_password }}"
        #   with_items: "{{ web_users }}"

        - name: Lock files for read only
          ansible.builtin.command:
            cmd: "mount -o remount,ro /"
