---
- name: Playbook to configure a PiKVM
  hosts:
    - pikvm
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Configure PiKVM
      ansible.builtin.include_role:
        name: ol3d.pikvm
