---
k3s-cluster:
  children:
    k3s-server:
      hosts:
        k3s-server-01:
          ansible_host: k3s-server-01.{{ public_domain }}
        k3s-server-02:
          ansible_host: k3s-server-02.{{ public_domain }}
        k3s-server-03:
          ansible_host: k3s-server-03.{{ public_domain }}
      vars:
        ansible_port: 22
        ansible_connection: ssh
    k3s-agent:
      hosts:
        k3s-agent-01:
          ansible_host: k3s-agent-01.{{ public_domain }}
        k3s-agent-02:
          ansible_host: k3s-agent-02.{{ public_domain }}
        k3s-agent-03:
          ansible_host: k3s-agent-03.{{ public_domain }}
      vars:
        ansible_port: 22
        ansible_connection: ssh
