kind: Secret
ansible_user: ENC[AES256_GCM,data:YclM5w==,iv:VIbH1DDRUXib1pD6HXYVflawY1Nd/O9DXwKiRbeuJEY=,tag:XzR7arg8RLOZhSi/11mtzQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:o6Q+mmX4FN7C54QrleWi,iv:q2+IbOHnc5EY1Ubj6o4goyos9PBC2MExKHqJJm4qPL0=,tag:iME7VrjVf/2nl5ZSpph1MA==,type:str]
ansible_ssh_pass: ENC[AES256_GCM,data:d1oviBVMlABydtpSUi9M,iv:xu4EVolYb/J0bVCt9WZeDWz/aBPvjQ3ZMgijjqT8H/I=,tag:idoYj/P7KPRWu3cYtdWhdA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-08T22:08:28Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAHPRmg8PLPFmxuawcPO+vlKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrmgpJMsRLjY7CqpGAgEQgDufwrBbQt6gjdkFGBjQZ+c8m6Ww6Hl3PO/X5fImIcL12qN5oV2aARMccuLygqP3GIXaYyWiV8OLc5pKGw==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-08T22:08:28Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgGvaC3IV8uTQ56g+hlKsQvrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM16CYmFi4jAhXC1PjAgEQgDsw2TROyKWQJbSlEie6YqNRG1iKqTcqle4YdtIKfREbyeJd/x3g8GKGCC6I60G5nENe6BzEFF8FFS6kyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T21:22:47Z"
    mac: ENC[AES256_GCM,data:842w/woVa/a2wb2diM40eZNKVuLoaANfdssXiwyqRnMD30LQSk652olwWrw04VmgIJlsn/TQppQESkcpxtO0mD8MxVgHxoRPwAdUpXtx+PzANlbqF5Nu39yXltOulQtVIANbNw2sANPwWU0S1C2Xdt/YlMcj7yZmFMIkXyrMxkA=,iv:YzWmkhWZzduH1cM1+cX1A8AHBe6PyTwJoAWQ0HEHdAc=,tag:8jPwGjieFIv9rxl0DCFhMw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
