---
- name: Docker node configuration
  hosts:
    - home-auto
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Configure hosts using included roles
      block:
        - name: Configure NTP settings
          ansible.builtin.include_role:
            name: geerlingguy.ntp

        - name: Configure unattended-upgrades using hifis.toolkit.unattended-upgrades role
          ansible.builtin.include_role:
            name: hifis.toolkit.unattended_upgrades

        - name: Configure Docker
          ansible.builtin.include_role:
            name: geerlingguy.docker

    # - block:
    #     - name: Update /etc/hosts file to contain all valid ip addresses
    #       ansible.builtin.template:
    #         src: "hosts.yaml.j2"
    #         dest: /etc/hosts
    #         mode: "0644"

    #     - name: Modify network interface definitions on pve hosts
    #       ansible.builtin.template:
    #         src: "interfaces.yaml.j2"
    #         dest: /etc/network/interfaces
    #         mode: "0644"
