---
- hosts: pve
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
        - name: Unmount disk to prevent use
          ansible.posix.mount:
            path: "{{ item }}"
            state: unmounted
          with_items: "{{ ceph_devices }}"
        - name: Zap the drives
          ansible.builtin.shell: >
            sgdisk --zap-all {{ item }} || true
          loop:
            - "{{ ceph_devices | default([]) }}"
        - name: Remove lvm partitions
          ansible.builtin.shell: "{{ item }}"
          loop:
            - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
            - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
            - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
            - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %
        - name: Wipe the block device
          ansible.builtin.command:
            cmd: "wipefs -af {{ item }}"
          with_items:
            - "{{ ceph_devices | default([]) }}"
