---
- hosts:
    - pve-cluster
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - block:
        - name: Register BIOS Version Var
          ansible.builtin.command:
            cmd: dmidecode -s bios-version
          register: bios_versions_list
          changed_when: false

        - name: Output BIOS Information
          ansible.builtin.debug:
            msg: "BIOS Version: {{ bios_versions_list.stdout }}"

        # - name: Register Proxmox Kernel Version
        #   ansible.builtin.command:
        #     cmd: pveversion
        #   register: kernel_version
        #   changed_when: false

        # - name: Output registered kernel version
        #   ansible.builtin.debug:
        #     msg: "{{ kernel_version.stdout }}"
        #   when: kernel_version | version('6','<')

        # - name: Compare BIOS versions between nodes
        #   ansible.builtin.debug:
        #     msg: "{{ item }}"
        #   with_items: "{{ bios_versions_list.stdout }}"
        #   when: bios_versions_list.stdout | version(bios_version, 'eq')
