---
network:
  children:
    switch:
      hosts:
        c2960l:
          ansible_host: c2960l.{{ public_domain }}
        c2960lp:
          ansible_host: c2960lp.{{ public_domain }}
      vars:
        ansible_port: 22
        ansible_connection: ssh
