---
- hosts:
    - c2960l
    - c2960lp
  gather_facts: false
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
        - name: run show version on the routers
          ios_command:
            commands: show version | incl Version
          register: output

        - name: print output
          debug:
            var: output.stdout_lines

    - block:
        - name: Configure Hostname
          cisco.ios.ios_hostname:
            config:
              hostname: "{{ hostname }}"
            state: merged

    # - block:
    #     - name: Configure System
    #       cisco.ios.ios_system:
    #         hostname: "{{ hostname }}"
    #         domain_name: "{{ public_domain }}"

    - block:
        - name: Configure VLANs
          cisco.ios.ios_vlans:
            config:
              - name: "{{ item.name }}"
                vlan_id: "{{ item.vlan_id }}"
                state: "{{ item.state }}"
                shutdown: "{{ item.shutdown }}"
                remote_span: "{{ item.remote_span }}"
            state: merged
          with_items: "{{ vlans }}"

        - name: Configure Access Interfaces
          cisco.ios.ios_l2_interfaces:
            config:
              - access:
                  vlan: "{{ item.access.vlan }}"
                mode: "{{ item.mode }}"
                name: "{{ item.name }}"
            state: merged
          with_items: "{{ access_interfaces }}"

        - name: Configure LAG Interfaces
          cisco.ios.ios_lag_interfaces:
            config:
              - name: "{{ item.0.name }}"
                members:
                  - member: "{{ item.1.member }}"
                    mode: "{{ item.1.mode }}"
            state: merged
          loop: "{{ lag_interfaces | subelements('members') }}"

        - name: Configure Trunk Interfaces
          cisco.ios.ios_l2_interfaces:
            config:
              - trunk:
                  allowed_vlans: "{{ item.trunk.allowed_vlans }}"
                  native_vlan: "{{ omit if item.trunk.native_vlan == 1 else item.trunk.native_vlan }}"
                mode: "{{ item.mode }}"
                name: "{{ item.name }}"
            state: merged
          with_items: "{{ trunk_interfaces }}"

    - block:
        - name: Save configuration to memory
          ios_command:
            commands: write memory
