---
- hosts:
    - c2960l
  gather_facts: false
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - block:
        - name: run show version on the routers
          ios_command:
            commands: show version | incl Version
          register: output

        - name: print output
          debug:
            var: output.stdout_lines

    - block:
        - name: Configure VLANs
          cisco.ios.ios_vlans:
            config:
              - name: "{{ item.name }}"
                vlan_id: "{{ item.vlan_id }}"
                state: "{{ item.state }}"
                shutdown: "{{ item.shutdown }}"
                remote_span: "{{ item.remote_span }}"
            state: merged
          with_items: "{{ vlans }}"

        - name: Configure Access Interfaces
          cisco.ios.ios_l2_interfaces:
            config:
              - access:
                  vlan: "{{ item.access.vlan }}"
                mode: "{{ item.mode }}"
                name: "{{ item.name }}"
            state: merged
          with_items: "{{ access_interfaces }}"

        - name: Configure Trunk Interfaces
          cisco.ios.ios_l2_interfaces:
            config:
              - trunk:
                  allowed_vlans: "{{ item.trunk.allowed_vlans }}"
                  # Default vlan is 1
                  native_vlan: "{{ item.trunk.native_vlan }}"
                mode: "{{ item.mode }}"
                name: "{{ item.name }}"
            state: merged
          with_items: "{{ trunk_interfaces }}"

        - name: Configure LAG Interfaces
          cisco.ios.ios_lag_interfaces:
            config:
              - name: "{{ item.name }}"
                members:
                  - member: GigabitEthernet0/45
                    mode: auto
                  - member: GigabitEthernet0/47
                    mode: auto
            state: merged
          with_items: "{{ lag_interfaces }}"

    - block:
        - name: Save configuration to memory
          ios_command:
            commands: write memory

# ---
# - hosts:
#     - c2960lp
#   gather_facts: false
#   any_errors_fatal: true

#   pre_tasks:
#     - name: Pausing for 2 seconds...
#       ansible.builtin.pause:
#         seconds: 2

#   tasks:
#     - block:
#         - name: run show version on the routers
#           ios_command:
#             commands: show version | incl Version
#           register: output

#         - name: print output
#           debug:
#             var: output.stdout_lines
