kind: Secret
passphrase: ENC[AES256_GCM,data:ibq34+FovTstiBFqrIyN,iv:aB484tKdIcz6PoU63415PLEdpTK4T8x0+qS/4xio7QE=,tag:2q52w8faXF4cHeuxpxmi0A==,type:str]
user: ENC[AES256_GCM,data:rxGxzA==,iv:ldG5Twzzja/US15QZZJmAmdPPsrHizvdfRYp2wpxUhk=,tag:sk9wtGknF36Wbcjw/3KBIw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:707904332389:key/a7f77b88-3d50-474a-a8a9-59aa09144204
          created_at: "2022-08-08T21:20:42Z"
          enc: AQICAHhHZwPv1OIZb1DNAdaRKOKtYkqWmSpD9UeJdPsAhZ3jAAHXdbDE/5+82FTDRCGIIZFmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPUch6AREUvRoRpOEAgEQgDtFTAGW8ikcD2x5smHCwN9Ocq1CCiU8z922HVkXBl0NoIWoTC9kIm5nr+bMF94CQfg1JwU/Vm8DoD0faw==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:707904332389:key/1484f301-4df8-4a1f-83d3-f3deb55e2607
          created_at: "2022-08-08T21:20:42Z"
          enc: AQICAHhcehfqcrV6HneBNt5T8nzvzmkknNyHROLBmk5R2QYGsgHNOuoX6SLU/TrnzaZ0FjH4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkttJY1CCDFXKpm/6AgEQgDt/200urLZf1KvcI3jtDPVnJMMQqeFnN69FkPOS8yvHzbxieNQgBFenRuTjcX5BkVM2p+x6APAFHI/91A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-08T21:52:21Z"
    mac: ENC[AES256_GCM,data:guNCg7un6o3R2YgESXpogKOpCy89W5kFNxLrvY7f7ucdBPuD5IyFW19yvf5PR1RAAzWsdxB6ZWVZWxTbUQmktdplq53lNzO1FgTZrYF6MvgRa4bOgs3bFKFAE9aoTYWGSSiMteJxrefytDbBKiUmpMYbL99mD34s8fYYJM+XCQY=,iv:ZLGufDSGaecnG+wmGi1VH1uH4F2bbGoaAV+D+IbxBHo=,tag:Mm00Hy/EmFvFRz4UGN66Yg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
