kind: Secret
ansible_user: ENC[AES256_GCM,data:gKQ5Md4bzFjp,iv:qObRHYGb73iv5yVbgFGfOtLSwU3UBDdnehkSRf4uZCA=,tag:WePdmwfL/AHn4XNwuYvkMA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BEj4TbBJ5LXDxbQXznZe,iv:ns2SV6+D2v67PThHb0dg+OMsDsxxzYO0CyfKnfa2dUQ=,tag:tb2hutz8f3QYL0ghQbC8mA==,type:str]
ansible_connection: ENC[AES256_GCM,data:IPftlnk=,iv:hoZixPzXVb3vxqvoOzxf3a+Mdgv1HQGrdeBWt4Qu1aY=,tag:jC18cBqZpc+0k368RTrSIQ==,type:str]
personal:
    email: ENC[AES256_GCM,data:M+kUywGmLL0ulLssHPTNS1X4YA==,iv:x/wnYjJiSRP7bwmxeyG12wiXwJCk5nS2ln0qWUDM494=,tag:GCkh7lauhDCyWxBjD0cKwg==,type:str]
    name: ENC[AES256_GCM,data:sOmBwZswhpvQ,iv:S1VlGg+Xc/NbwOQqm83f69xQUwbymSd2aBjrGmYfrJo=,tag:F5de/czyxPFrClKVvLeEvg==,type:str]
aws:
    credentials:
        default:
            access_key_id: ENC[AES256_GCM,data:bIIp7lZGc4o2OoFyfb+wK2WPlL8=,iv:EBO8ONIjFLUTFjKQ+Gpy651KWpechFw8EyVJNPBVgh4=,tag:AQ0IUGmKw7LR20OQbIPCpw==,type:str]
            secret_access_key: ENC[AES256_GCM,data:/0Ba5M65fQ7IMsXVxtoZA+svtB7R0+e9c3e6GfqATfFqoeaKXOeq6A==,iv:0FEHND51pQ4Y1i1LzKHlSILas+9zouGZhh8xMyUS/6E=,tag:bJb/jPOIawNiLyh6LznK/g==,type:str]
        terraform:
            access_key_id: ENC[AES256_GCM,data:EsE2IUqvXMu9QWNp9S6wPbSK0uc=,iv:W6Qzf4T7WDI8o5NfPA9tYr4IDJwXA362S9WpwNZSKK4=,tag:jMOanjRWDY2kifu/PjRbDg==,type:str]
            secret_access_key: ENC[AES256_GCM,data:SM0DXcDBe8RmyS6uKhPeAXp0IWfjMNLyJWT00bfnqJqICX71fRa8Ng==,iv:jCKoAzREN6muYhrGhJAfIXF7d4p3oUkn8yqzsM9ce7c=,tag:uAHcn71F/T4U9t9s2gqTDA==,type:str]
        packer:
            access_key_id: ENC[AES256_GCM,data:nckkqOKsm7LPPKMivwynyTCq6/0=,iv:KUDfy88aica0+9vhkYdcs/Gk4hJ/C8fBMr/7PAMsT+U=,tag:U8mKJsrciLokvDKbSmO9eQ==,type:str]
            secret_access_key: ENC[AES256_GCM,data:ReCKrdMZ447oF0Oo9UD/vmyyIDP3ifz7ZCfwI3pomr19HxxDixBwxg==,iv:YiTl0IDpO6v0XP362j5yHovbagw9wlj1h9hhcXBKcd0=,tag:NW1NdkPnYqJ42AC+1v5svQ==,type:str]
    config:
        default:
            region: ENC[AES256_GCM,data:zzh2PEKrovbO,iv:sP1+xX94r/wCY5XgRJvQ7dYtjof4eyV0TabwkMDghqg=,tag:oKc3WpH1bpSSqwAlFNKkYw==,type:str]
        terraform:
            region: ENC[AES256_GCM,data:Z6TsRdExKvfg,iv:aPUkrUCHmucDTIKgAH1o+NbHtJ5Rn+QpUUe3upfkFlU=,tag:Y9oX0Ymf4+Z5V6pRVJH39w==,type:str]
        packer:
            region: ENC[AES256_GCM,data:HJooTstEq6F6,iv:ZnGdJk3nYZ0/39iOECdoFMXW5JaAdDc2l0H/i5LYyGw=,tag:LJpTj/jL/GTIQZRZpXLGsg==,type:str]
git_repositories:
    - repo: ENC[AES256_GCM,data:M22isDavFmry0MhuGFsv2zLVaMRClXYqdljaZXGTCbdIH7fA,iv:OZoCw3AvvK5vICsUJ4ovNvv4q3y4EJWJ+CJJyu0XOA0=,tag:R0CzNVzUal2Tun43Ox7q5w==,type:str]
      dest: ENC[AES256_GCM,data:zU+3gs01ocs=,iv:LO3oS3GmpFzZH4qSaPeFkpsjfPn9JbQm8wr9CTjg+as=,tag:YCqP1PuNhiuqkJxv77Fz/Q==,type:str]
    - repo: ENC[AES256_GCM,data:7BkJR783EG+n1yfbJcRPo5uwui0dVh3r9HAQZuIwCb4=,iv:CSMCGisipSGJWgZoA4fYgF4OuKVm35Jh309bkRXcK2Q=,tag:2Sb2+lpNtJBe4PCUdKg82Q==,type:str]
      dest: ENC[AES256_GCM,data:PNfuuA==,iv:J1G5b+fYgG6fcuS80qWN2y3LolR+fsCNjddUHf6UUtk=,tag:6we6rm0dNDchsfWlZ5ZxVg==,type:str]
    - repo: ENC[AES256_GCM,data:nERqBAclQnXjLEQTm+nPiaY0TCI5WMkgt1ufnSzeiAV70HStt7jgysiG,iv:RZk3dAwiDF6kynSUt02YhzC2pBKogSFDBa4pfuXNTmc=,tag:OG9QdgjqCu1/bmN+OHjCsw==,type:str]
      dest: ENC[AES256_GCM,data:KYLsw7zsh590FoOBCpE=,iv:vjn6VmFIvFA7c2pYQnkQKUQ8qA0yoL+CZQzuM+wvXH0=,tag:ulu9FH+wH+bzzAS9599/AA==,type:str]
    - repo: ENC[AES256_GCM,data:hg61UwTeAOKaqx4Q9t9XCJdMoKrFQKppq21s5ubD1n1ipvY=,iv:RB9eikH3wpDAc+M2IWVoqWg0dNs4uFMBcQFaHg6J3r4=,tag:cuuE0xOyJMIpMquJ9BJW9w==,type:str]
      dest: ENC[AES256_GCM,data:+hmOnsDVCQ==,iv:YbOucTSXjqouBXcaaKIqm891YPO/M4KY5/TFVsHQ1+o=,tag:c7VICfXYg6C9EIuLpmIg8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTEpXSGFHWWNUSGdCc2h2
            bVdWNWY1Tk5PaEF3QmFKeHhVWEI1RTRuNkU4ClVFVnU4M0hHenlqbFRCTlBaUzFN
            dXBXcUdoUWRGWmJnS3Y5dU80Wi83ZGsKLS0tIEdhdGh3TldRcDdRNUVQcTNGWVUz
            MFd4L3RYRWNvL253UDMyblJ4dzRidDQKRw+otwqPojYzjv0C6Y7LDDRMEWdbyf8m
            izIgT9xfLxn9mPASHjhzjIniHZSb3eyr/bvBYnE7/nSFpbzMyylTfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:08:00Z"
    mac: ENC[AES256_GCM,data:v05HN+IyBs1SoOBoFbzngDNo2WlYpWf8IoXXcLhf07fikjTJ6FJY9ztJRBain6ZkvdwTUmc1FcAtnt28XH9RpZ+UYnWyfLwSSx4sJbUrHAV5vJKx+pff7fnQaMqN0BXTGIqEeZ1YGdX704jKo/SG+giJtrgHfX8i2j07bT2WlsM=,iv:n7PbTFErvT601A5XuRAxjv0rJE6j8Ys8Suh+55wOz9o=,tag:H31lhRqgyPMe7rUHqdeG6A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
