kind: Secret
ansible_user: ENC[AES256_GCM,data:gKQ5Md4bzFjp,iv:qObRHYGb73iv5yVbgFGfOtLSwU3UBDdnehkSRf4uZCA=,tag:WePdmwfL/AHn4XNwuYvkMA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BEj4TbBJ5LXDxbQXznZe,iv:ns2SV6+D2v67PThHb0dg+OMsDsxxzYO0CyfKnfa2dUQ=,tag:tb2hutz8f3QYL0ghQbC8mA==,type:str]
ansible_connection: ENC[AES256_GCM,data:IPftlnk=,iv:hoZixPzXVb3vxqvoOzxf3a+Mdgv1HQGrdeBWt4Qu1aY=,tag:jC18cBqZpc+0k368RTrSIQ==,type:str]
personal:
    email: ENC[AES256_GCM,data:M+kUywGmLL0ulLssHPTNS1X4YA==,iv:x/wnYjJiSRP7bwmxeyG12wiXwJCk5nS2ln0qWUDM494=,tag:GCkh7lauhDCyWxBjD0cKwg==,type:str]
    name: ENC[AES256_GCM,data:sOmBwZswhpvQ,iv:S1VlGg+Xc/NbwOQqm83f69xQUwbymSd2aBjrGmYfrJo=,tag:F5de/czyxPFrClKVvLeEvg==,type:str]
git_repositories:
    - repo: ENC[AES256_GCM,data:0GMYEKsUquTJSWH8U23zgnouEQxynOZ3AaqPPPHrU4Y=,iv:erYVXG/zpYcClp4iEU1PhC0cZJAb4Fu8oXlXMfMTBFE=,tag:9B5qLTVuX3g5dudvvQsjiA==,type:str]
      dest: ENC[AES256_GCM,data:zU+3gs01ocs=,iv:LO3oS3GmpFzZH4qSaPeFkpsjfPn9JbQm8wr9CTjg+as=,tag:YCqP1PuNhiuqkJxv77Fz/Q==,type:str]
    - repo: ENC[AES256_GCM,data:7BkJR783EG+n1yfbJcRPo5uwui0dVh3r9HAQZuIwCb4=,iv:CSMCGisipSGJWgZoA4fYgF4OuKVm35Jh309bkRXcK2Q=,tag:2Sb2+lpNtJBe4PCUdKg82Q==,type:str]
      dest: ENC[AES256_GCM,data:PNfuuA==,iv:J1G5b+fYgG6fcuS80qWN2y3LolR+fsCNjddUHf6UUtk=,tag:6we6rm0dNDchsfWlZ5ZxVg==,type:str]
    - repo: ENC[AES256_GCM,data:nERqBAclQnXjLEQTm+nPiaY0TCI5WMkgt1ufnSzeiAV70HStt7jgysiG,iv:RZk3dAwiDF6kynSUt02YhzC2pBKogSFDBa4pfuXNTmc=,tag:OG9QdgjqCu1/bmN+OHjCsw==,type:str]
      dest: ENC[AES256_GCM,data:KYLsw7zsh590FoOBCpE=,iv:vjn6VmFIvFA7c2pYQnkQKUQ8qA0yoL+CZQzuM+wvXH0=,tag:ulu9FH+wH+bzzAS9599/AA==,type:str]
    - repo: ENC[AES256_GCM,data:hg61UwTeAOKaqx4Q9t9XCJdMoKrFQKppq21s5ubD1n1ipvY=,iv:RB9eikH3wpDAc+M2IWVoqWg0dNs4uFMBcQFaHg6J3r4=,tag:cuuE0xOyJMIpMquJ9BJW9w==,type:str]
      dest: ENC[AES256_GCM,data:+hmOnsDVCQ==,iv:YbOucTSXjqouBXcaaKIqm891YPO/M4KY5/TFVsHQ1+o=,tag:c7VICfXYg6C9EIuLpmIg8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6wldgwdcte6aq4cljv3rn5zdxwft4h6pksky0uwhf2z52d7cvtszhs0cv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTEpXSGFHWWNUSGdCc2h2
            bVdWNWY1Tk5PaEF3QmFKeHhVWEI1RTRuNkU4ClVFVnU4M0hHenlqbFRCTlBaUzFN
            dXBXcUdoUWRGWmJnS3Y5dU80Wi83ZGsKLS0tIEdhdGh3TldRcDdRNUVQcTNGWVUz
            MFd4L3RYRWNvL253UDMyblJ4dzRidDQKRw+otwqPojYzjv0C6Y7LDDRMEWdbyf8m
            izIgT9xfLxn9mPASHjhzjIniHZSb3eyr/bvBYnE7/nSFpbzMyylTfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T21:00:49Z"
    mac: ENC[AES256_GCM,data:Vj+wDOYoF3PmKW7rQtyybGQ0JE30aVQ0ORbLMXKLHubN3Ji3jdmO3SJOqJCcjOHP7ephv9yRe5M7cm7mTaODtA87mN56JhHzoOG7zu3ueKIgLzza5dZjkJNxDmLoUmFOYnbW7hKIaP7uWJDvpSnY097MxuyFv8BljvZwA6pVRqE=,iv:d1coDyKnh8sLje+b+TbrfpXkmvV1hvKM81z8qtVuduM=,tag:OoQdkKyRqJTPEYr+AgbA7g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
